### ISSUE TITLE
シンプルなメニューアイテム機能の実装

### ISSUE THREAD

**Issue by YukiLeafX** [AzisabaNetwork/LeonGunWar#16]
## 原案
![unknown](https://user-images.githubusercontent.com/33691365/70866579-d960ed00-1fae-11ea-9b6c-f689a0ac87b4.png)

**Comment by YukiLeafX** [comment]
```yml
panels:
  LGWMenu:
    perm: default
    rows: '6'
    title: '&6&lLGWメニュー'
    command: LGWMenu
    empty: AIR
    animate-delay: '4'
    item:
      '0':
        material: STAINED_GLASS_PANE
        ID: 3
        name: '&4&l運営メニュー'
        lore:
        - '&4&o一般プレイヤーには見えません'
        commands:
        - op= cp Opmenu <player>
        noperm:
          perm: essentials.gamemode
          material: STAINED_GLASS_PANE
          ID: 5
      '1':
        material: STAINED_GLASS_PANE
        ID: 5
      '2':
        material: STAINED_GLASS_PANE
        ID: 5
      '3':
        material: STAINED_GLASS_PANE
        ID: 5
      '4':
        material: STAINED_GLASS_PANE
        ID: 5
      '5':
        material: STAINED_GLASS_PANE
        ID: 5
      '6':
        material: STAINED_GLASS_PANE
        ID: 5
      '7':
        material: STAINED_GLASS_PANE
        ID: 5
      '8':
        material: STAINED_GLASS_PANE
        ID: 5
      '9':
        material: STAINED_GLASS_PANE
        ID: 5
      '10':
        material: STAINED_GLASS_PANE
        ID: 14
      '11':
        material: STAINED_GLASS_PANE
        ID: 14
      '12':
        material: STAINED_GLASS_PANE
        ID: 14
      '13':
        material: STAINED_GLASS_PANE
        ID: 14
      '14':
        material: STAINED_GLASS_PANE
        ID: 14
      '15':
        material: STAINED_GLASS_PANE
        ID: 14
      '16':
        material: STAINED_GLASS_PANE
        ID: 14
      '17':
        material: STAINED_GLASS_PANE
        ID: 5
      '18':
        material: STAINED_GLASS_PANE
        ID: 5
      '19':
        material: STAINED_GLASS_PANE
        ID: 14
      '20':
        material: COMPASS
        name: '&b&lロビーに戻る'
        commands:
        - op= spawn <player>
      '21':
        material: GRASS
        name: '&2&lTP場所一覧'
        commands:
        - op= cp TPListPanel <player>
      '22':
        material: EMERALD
        name: '&a&lSHOP一覧'
        commands:
        - op= cp ShopListPanel <player>
      '23':
        material: DIAMOND_SWORD
        name: '&4&l試合'
        lore:
        - '&a&o右クリック:エントリー'
        - '&4&oシフト右クリック:エントリー解除'
        - '&6&o左クリック:途中参加'
        commands:
        - right= op= match entry <player>
        - rightshift= op= match leave <player>
        - left= op= match rejoin <player>
      '24':
        material: GOLD_BLOCK
        name: '&6&l換金アイテム一覧'
        lore:
        - '&4&o換金する際インベントリに空きを作ってください'
        commands:
        - op= cp CraftListPanel <player>
      '25':
        material: STAINED_GLASS_PANE
        ID: 14
      '26':
        material: STAINED_GLASS_PANE
        ID: 5
      '27':
        material: STAINED_GLASS_PANE
        ID: 5
      '28':
        material: STAINED_GLASS_PANE
        ID: 14
      '29':
        material: DROPPER
        name: '&8&lごみ箱'
        commands:
        - trash <player>
      '30':
        material: SPECKLED_MELON
        name: '&d&lパーティクルメニュー'
        commands:
        - h open vip1
      '34':
        material: STAINED_GLASS_PANE
        ID: 14
      '35':
        material: STAINED_GLASS_PANE
        ID: 5
      '36':
        material: STAINED_GLASS_PANE
        ID: 5
      '37':
        material: STAINED_GLASS_PANE
        ID: 14
      '38':
        material: STAINED_GLASS_PANE
        ID: 14
      '39':
        material: STAINED_GLASS_PANE
        ID: 14
      '40':
        material: STAINED_GLASS_PANE
        ID: 14
      '41':
        material: STAINED_GLASS_PANE
        ID: 14
      '42':
        material: STAINED_GLASS_PANE
        ID: 14
      '43':
        material: STAINED_GLASS_PANE
        ID: 14
      '44':
        material: STAINED_GLASS_PANE
        ID: 5
      '45':
        material: STAINED_GLASS_PANE
        ID: 5
      '46':
        material: STAINED_GLASS_PANE
        ID: 5
      '47':
        material: STAINED_GLASS_PANE
        ID: 5
      '48':
        material: STAINED_GLASS_PANE
        ID: 5
      '49':
        material: STAINED_GLASS_PANE
        ID: 5
      '50':
        material: STAINED_GLASS_PANE
        ID: 5
      '51':
        material: STAINED_GLASS_PANE
        ID: 5
      '52':
        material: STAINED_GLASS_PANE
        ID: 5
      '53':
        material: BARRIER
        name: '&4&l閉じる'
        commands:
        - op= cpc
  ShopListPanel:
    perm: default
    rows: '5'
    title: '&a&lSHOP一覧'
    command: ShopListPanel
    empty: AIR
    animate-delay: '4'
    item:
      '0':
        material: STAINED_GLASS_PANE
        ID: 4
      '1':
        material: STAINED_GLASS_PANE
        ID: 4
      '2':
        material: STAINED_GLASS_PANE
        ID: 4
      '3':
        material: STAINED_GLASS_PANE
        ID: 4
      '4':
        material: STAINED_GLASS_PANE
        ID: 4
      '5':
        material: STAINED_GLASS_PANE
        ID: 4
      '6':
        material: STAINED_GLASS_PANE
        ID: 4
      '7':
        material: STAINED_GLASS_PANE
        ID: 4
      '8':
        material: STAINED_GLASS_PANE
        ID: 4
      '9':
        material: BONE
        name: '§8&lSG'
        commands:
        - teleport= 822 5 702 180 0
      '10':
        material: LEATHER
        name: '§8&lLMG'
        commands:
        - teleport= 822 5 690 180 0
      '11':
        material: BOWL
        name: '§8&lSMG'
        commands:
        - teleport= 882 5 690 180 0
      '12':
        material: IRON_PICKAXE
        name: '§8&lAR'
        commands:
        - teleport= 882 5 702 180 0
      '13':
        material: DIAMOND_HOE
        name: '§8&lHG'
        commands:
        - teleport= 882 5 714 180 0
      '14':
        material: SHEARS
        name: '§8&lSR'
        commands:
        - teleport= 822 5 714 180 0
      '18':
        material: WOOL
        ID: 7
        name: '§8&lNF&PF'
        commands:
        - teleport= 842 4 701 180 0
      '19':
        material: WOOL
        ID: 13
        name: '§2&lUF'
        commands:
        - teleport= 856 4 643 180 0
      '20':
        material: WOOL
        ID: 6
        name: '§d&lRF'
        commands:
        - teleport= 867 4 643 180 0
      '21':
        material: WOOL
        ID: 3
        name: '§b&lYF'
        commands:
        - teleport= 1284 5 470 180 0
      '36':
        material: STAINED_GLASS_PANE
        ID: 4
      '37':
        material: STAINED_GLASS_PANE
        ID: 4
      '38':
        material: STAINED_GLASS_PANE
        ID: 4
      '39':
        material: STAINED_GLASS_PANE
        ID: 4
      '40':
        material: STAINED_GLASS_PANE
        ID: 4
      '41':
        material: STAINED_GLASS_PANE
        ID: 4
      '42':
        material: STAINED_GLASS_PANE
        ID: 4
      '43':
        material: STAINED_GLASS_PANE
        ID: 7
        name: '&8&l戻る'
        commands:
        - op= cp LGWMenu <player>
      '44':
        material: BARRIER
        name: '&4&l閉じる'
        commands:
        - op= cpc
  TPListPanel:
    perm: default
    rows: '5'
    title: '&2&lTP一覧'
    command: TPListPanel
    empty: AIR
    animate-delay: '4'
    item:
      '0':
        material: STAINED_GLASS_PANE
        ID: 5
      '1':
        material: STAINED_GLASS_PANE
        ID: 5
      '2':
        material: STAINED_GLASS_PANE
        ID: 5
      '3':
        material: STAINED_GLASS_PANE
        ID: 5
      '4':
        material: STAINED_GLASS_PANE
        ID: 5
      '5':
        material: STAINED_GLASS_PANE
        ID: 5
      '6':
        material: STAINED_GLASS_PANE
        ID: 5
      '7':
        material: STAINED_GLASS_PANE
        ID: 5
      '8':
        material: STAINED_GLASS_PANE
        ID: 5
      '9':
        material: WATER_BUCKET
        name: '&9&l噴水公園'
        commands:
        - teleport= 876 4 676 -90 0
      '10':
        material: CONCRETE
        name: '&7&l街に出る'
        commands:
        - op= sbp interact run Lobby 831 4 748
      '11':
        material: BOW
        name: '&8&l射撃場'
        commands:
        - teleport= 815 4 732 90 0
      '12':
        material: LOG
        name: '&a&l憩いの場'
        ID: 1
        commands:
        - teleport= 896 4 718 180 0
      '13':
        material: STAINED_GLASS
        ID: 3
        name: '&4&lアスレ'
        lore:
        - '&4&o右クリック:初級'
        - '&4&oシフト右クリック:中級'
        - '&4&o左クリック:上級'
        commands:
        - right= op= sbp interact run Lobby 860 7 698
        - rightshift= op= sbp interact run Lobby 861 7 698
        - left= op= sbp interact run Lobby 862 7 698
      '14':
        material: GOLD_BLOCK
        name: '&6&l換金所'
        commands:
        - teleport= 1272 5 465 180 0
      '15':
        material: COMPASS
        name: '&5&l時計台'
        commands:
        - op= sbp interact run Lobby 895 5 636
      '36':
        material: STAINED_GLASS_PANE
        ID: 5
      '37':
        material: STAINED_GLASS_PANE
        ID: 5
      '38':
        material: STAINED_GLASS_PANE
        ID: 5
      '39':
        material: STAINED_GLASS_PANE
        ID: 5
      '40':
        material: STAINED_GLASS_PANE
        ID: 5
      '41':
        material: STAINED_GLASS_PANE
        ID: 5
      '42':
        material: STAINED_GLASS_PANE
        ID: 5
      '43':
        material: STAINED_GLASS_PANE
        ID: 7
        name: '&8&l戻る'
        commands:
        - op= cp LGWMenu <player>
      '44':
        material: BARRIER
        name: '&4&l閉じる'
        commands:
        - op= cpc
  CraftListPanel:
    perm: default
    rows: '5'
    title: '&6&l換金アイテム一覧'
    command: CraftListPanel
    empty: AIR
    animate-delay: '4'
    item:
      '0':
        material: STAINED_GLASS_PANE
        ID: 5
      '1':
        material: STAINED_GLASS_PANE
        ID: 5
      '2':
        material: STAINED_GLASS_PANE
        ID: 5
      '3':
        material: STAINED_GLASS_PANE
        ID: 5
      '4':
        material: STAINED_GLASS_PANE
        ID: 5
      '5':
        material: STAINED_GLASS_PANE
        ID: 5
      '6':
        material: STAINED_GLASS_PANE
        ID: 5
      '7':
        material: STAINED_GLASS_PANE
        ID: 5
      '8':
        material: STAINED_GLASS_PANE
        ID: 5
      '9':
        material: EMERALD_BLOCK
        name: '&a&lエメラルドブロック'
        lore:
        - 'シフト:63エメラルド一括換金'
        commands:
        - left= op= sbp interact run Lobby 1271 5 455
        - leftshift= op= sbp interact run Lobby 1271 5 454
      '10':
        material: DIAMOND_BLOCK
        name: '&b&lダイアモンドブロック'
        lore:
        - 'シフト:63ダイアモンド一括換金'
        commands:
        - left= op= sbp interact run Lobby 1273 5 455
        - leftshift= op= sbp interact run Lobby 1273 5 454
      '36':
        material: STAINED_GLASS_PANE
        ID: 5
      '37':
        material: STAINED_GLASS_PANE
        ID: 5
      '38':
        material: STAINED_GLASS_PANE
        ID: 5
      '39':
        material: STAINED_GLASS_PANE
        ID: 5
      '40':
        material: STAINED_GLASS_PANE
        ID: 5
      '41':
        material: STAINED_GLASS_PANE
        ID: 5
      '42':
        material: STAINED_GLASS_PANE
        ID: 5
      '43':
        material: STAINED_GLASS_PANE
        ID: 7
        name: '&8&l戻る'
        commands:
        - op= cp LGWMenu <player>
      '44':
        material: BARRIER
        name: '&4&l閉じる'
        commands:
        - op= cpc
```
CommandPanelsの設定コピペ
